import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['selector', '[data-theme="dark"]'],
  /* The frozen Kawaii Matsuri sheets are the authoritative base layer; Tailwind
     preflight would reset their typography, borders, and controls. */
  corePlugins: { preflight: false },
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)'],
        round: ['var(--font-round)'],
        body: ['var(--font-body)'],
      },
      fontSize: {
        'display-xl': ['var(--type-display-xl)', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'display-l': ['var(--type-display-l)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-m': ['var(--type-display-m)', { lineHeight: '1.08', letterSpacing: '-0.01em' }],
        'display-s': ['var(--type-display-s)', { lineHeight: '1.12', letterSpacing: '-0.01em' }],
        h1: ['var(--type-h1)', { lineHeight: '1.20' }],
        h2: ['var(--type-h2)', { lineHeight: '1.25' }],
        h3: ['var(--type-h3)', { lineHeight: '1.30' }],
        h4: ['var(--type-h4)', { lineHeight: '1.35' }],
        'body-l': ['var(--type-body-l)', { lineHeight: '1.60' }],
        body: ['var(--type-body)', { lineHeight: '1.65' }],
        'body-s': ['var(--type-body-s)', { lineHeight: '1.60' }],
        caption: ['var(--type-caption)', { lineHeight: '1.50' }],
        label: ['var(--type-label)', { lineHeight: '1.35' }],
        overline: ['var(--type-overline)', { lineHeight: '1.40', letterSpacing: '0.10em' }],
        badge: ['var(--type-badge)', { lineHeight: '1.20' }],
        'mono-num': ['var(--type-mono-num)', { lineHeight: '1.20' }],
        'kanji-xl': ['var(--type-kanji-xl)', { lineHeight: '1.0' }],
        'kanji-l': ['var(--type-kanji-l)', { lineHeight: '1.0' }],
        'kanji-m': ['var(--type-kanji-m)', { lineHeight: '1.0' }],
      },
      lineHeight: {
        tight: 'var(--lh-tight)',
        body: 'var(--lh-body)',
      },
      letterSpacing: {
        tight: 'var(--letter-tight)',
        normal: 'var(--letter-normal)',
        wide: 'var(--letter-wide)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        row: 'var(--row-h)',
        'row-mobile': 'var(--row-h-mobile)',
        rail: 'var(--rail-w)',
        'rail-md': 'var(--rail-w-md)',
        'rail-gap': 'var(--rail-gap)',
        'rail-cover': 'var(--rail-cover-h)',
        'rail-tab': 'var(--rail-tab-h)',
        tabbar: 'var(--tabbar-h)',
        topbar: 'var(--topbar-h)',
        crease: 'var(--crease-w)',
        'mosaic-gap': 'var(--mosaic-gap)',
        'mosaic-row-gap': 'var(--mosaic-row-gap)',
        'mosaic-row': 'var(--mosaic-row-h)',
        'spread-seam': 'var(--spread-seam-w)',
        postcard: 'var(--postcard-w)',
        reply: 'var(--reply-w)',
        'notebook-spiral': 'var(--notebook-spiral-w)',
        stamp: 'var(--stamp-size)',
        frame: 'var(--frame-w)',
        'tape-page': 'var(--tape-page-w)',
        'tape-corner': 'var(--tape-corner-w)',
        'photo-corner': 'var(--photo-corner)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        sticker: 'var(--radius-sticker)',
        hanko: 'var(--radius-hanko)',
        seal: 'var(--radius-seal)',
      },
      borderWidth: {
        DEFAULT: 'var(--border-w)',
        thin: 'var(--border-w-thin)',
        hair: 'var(--border-w-hair)',
      },
      maxWidth: {
        narrow: 'var(--container-narrow)',
        form: 'var(--container-form)',
        content: 'var(--container-content)',
        wide: 'var(--container-wide)',
        admin: 'var(--container-admin)',
        'template-collage': 'var(--template-collage)',
        'template-spread': 'var(--template-spread)',
        'template-notebook': 'var(--template-notebook)',
        'template-guestbook': 'var(--template-guestbook)',
        'template-clipboard': 'var(--template-clipboard)',
        'template-ledger': 'var(--template-ledger)',
        'template-cover': 'var(--template-cover)',
        'template-guide': 'var(--template-guide)',
        canvas: 'var(--canvas-max)',
      },
      boxShadow: {
        paper: 'var(--shadow-paper)',
        lift: 'var(--shadow-lift)',
        raised: 'var(--shadow-raised)',
        modal: 'var(--shadow-modal)',
        sticker: 'var(--shadow-sticker)',
        'glow-coral': 'var(--shadow-glow-coral)',
        'glow-sky': 'var(--shadow-glow-sky)',
        'glow-sun': 'var(--shadow-glow-sun)',
        'glow-leaf': 'var(--shadow-glow-leaf)',
        tabbar: 'var(--tabbar-shadow)',
      },
      zIndex: {
        base: 'var(--z-base)',
        pattern: 'var(--z-pattern)',
        crease: 'var(--z-crease)',
        tile: 'var(--z-tile)',
        sticky: 'var(--z-sticky)',
        'tile-hover': 'var(--z-tile-hover)',
        nav: 'var(--z-nav)',
        rail: 'var(--z-rail)',
        drawer: 'var(--z-drawer)',
        tabbar: 'var(--z-tabbar)',
        dropdown: 'var(--z-dropdown)',
        tape: 'var(--z-tape)',
        sticker: 'var(--z-sticker)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        confetti: 'var(--z-confetti)',
        'focus-skip': 'var(--z-focus-skip)',
      },
      transitionDuration: {
        instant: 'var(--dur-instant)',
        fast: 'var(--dur-fast)',
        quick: 'var(--dur-quick)',
        base: 'var(--dur-base)',
        medium: 'var(--dur-medium)',
        slow: 'var(--dur-slow)',
        slower: 'var(--dur-slower)',
        'tile-settle': 'var(--dur-tile-settle)',
        'tape-peel': 'var(--dur-tape-peel)',
        'page-turn': 'var(--dur-page-turn)',
        drawer: 'var(--dur-drawer)',
        stamp: 'var(--dur-stamp)',
        'idle-wobble': 'var(--dur-idle-wobble)',
        'idle-beckon': 'var(--dur-idle-beckon)',
        'idle-koi': 'var(--dur-idle-koi)',
        'idle-nod': 'var(--dur-idle-nod)',
      },
      transitionTimingFunction: {
        paper: 'var(--ease-paper)',
        press: 'var(--ease-press)',
        snap: 'var(--ease-snap)',
        rip: 'var(--ease-rip)',
        bob: 'var(--ease-bob)',
        anticipate: 'var(--ease-anticipate)',
        'page-turn': 'var(--ease-page-turn)',
      },
      width: {
        'mascot-xs': 'var(--mascot-xs)',
        'mascot-sm': 'var(--mascot-sm)',
        'mascot-md': 'var(--mascot-md)',
        'mascot-lg': 'var(--mascot-lg)',
        'mascot-xl': 'var(--mascot-xl)',
      },
      height: {
        'mascot-xs': 'var(--mascot-xs)',
        'mascot-sm': 'var(--mascot-sm)',
        'mascot-md': 'var(--mascot-md)',
        'mascot-lg': 'var(--mascot-lg)',
        'mascot-xl': 'var(--mascot-xl)',
        'btn-sm': 'var(--btn-h-sm)',
        'btn-md': 'var(--btn-h-md)',
        'btn-lg': 'var(--btn-h-lg)',
      },
      colors: {
        cream: {
          50: 'var(--cream-50)',
          100: 'var(--cream-100)',
          200: 'var(--cream-200)',
          300: 'var(--cream-300)',
          400: 'var(--cream-400)',
          500: 'var(--cream-500)',
          600: 'var(--cream-600)',
          700: 'var(--cream-700)',
          800: 'var(--cream-800)',
        },
        sumi: {
          50: 'var(--sumi-50)',
          100: 'var(--sumi-100)',
          200: 'var(--sumi-200)',
          300: 'var(--sumi-300)',
          400: 'var(--sumi-400)',
          500: 'var(--sumi-500)',
          600: 'var(--sumi-600)',
          700: 'var(--sumi-700)',
          800: 'var(--sumi-800)',
        },
        sakura: {
          50: 'var(--sakura-50)',
          100: 'var(--sakura-100)',
          200: 'var(--sakura-200)',
          300: 'var(--sakura-300)',
          400: 'var(--sakura-400)',
          500: 'var(--sakura-500)',
          600: 'var(--sakura-600)',
          700: 'var(--sakura-700)',
          800: 'var(--sakura-800)',
        },
        sora: {
          50: 'var(--sora-50)',
          100: 'var(--sora-100)',
          200: 'var(--sora-200)',
          300: 'var(--sora-300)',
          400: 'var(--sora-400)',
          500: 'var(--sora-500)',
          600: 'var(--sora-600)',
          700: 'var(--sora-700)',
          800: 'var(--sora-800)',
        },
        wakatake: {
          50: 'var(--wakatake-50)',
          100: 'var(--wakatake-100)',
          200: 'var(--wakatake-200)',
          300: 'var(--wakatake-300)',
          400: 'var(--wakatake-400)',
          500: 'var(--wakatake-500)',
          600: 'var(--wakatake-600)',
          700: 'var(--wakatake-700)',
          800: 'var(--wakatake-800)',
        },
        yamabuki: {
          50: 'var(--yamabuki-50)',
          100: 'var(--yamabuki-100)',
          200: 'var(--yamabuki-200)',
          300: 'var(--yamabuki-300)',
          400: 'var(--yamabuki-400)',
          500: 'var(--yamabuki-500)',
          600: 'var(--yamabuki-600)',
          700: 'var(--yamabuki-700)',
          800: 'var(--yamabuki-800)',
        },
        shu: {
          50: 'var(--shu-50)',
          100: 'var(--shu-100)',
          200: 'var(--shu-200)',
          300: 'var(--shu-300)',
          400: 'var(--shu-400)',
          500: 'var(--shu-500)',
          600: 'var(--shu-600)',
          700: 'var(--shu-700)',
          800: 'var(--shu-800)',
        },
        matcha: {
          50: 'var(--matcha-50)',
          100: 'var(--matcha-100)',
          200: 'var(--matcha-200)',
          300: 'var(--matcha-300)',
          400: 'var(--matcha-400)',
          500: 'var(--matcha-500)',
          600: 'var(--matcha-600)',
          700: 'var(--matcha-700)',
          800: 'var(--matcha-800)',
        },
        fuji: {
          50: 'var(--fuji-50)',
          100: 'var(--fuji-100)',
          200: 'var(--fuji-200)',
          300: 'var(--fuji-300)',
          400: 'var(--fuji-400)',
          500: 'var(--fuji-500)',
          600: 'var(--fuji-600)',
          700: 'var(--fuji-700)',
          800: 'var(--fuji-800)',
        },
        indigo: {
          50: 'var(--indigo-50)',
          100: 'var(--indigo-100)',
          200: 'var(--indigo-200)',
          300: 'var(--indigo-300)',
          400: 'var(--indigo-400)',
          500: 'var(--indigo-500)',
          600: 'var(--indigo-600)',
          700: 'var(--indigo-700)',
          800: 'var(--indigo-800)',
          900: 'var(--indigo-900)',
        },
        surface: {
          page: 'var(--surface-page)',
          paper: 'var(--surface-paper)',
          raised: 'var(--surface-raised)',
          sunken: 'var(--surface-sunken)',
          ink: 'var(--surface-ink)',
          'tint-rose': 'var(--surface-tint-rose)',
          'tint-sky': 'var(--surface-tint-sky)',
          'tint-leaf': 'var(--surface-tint-leaf)',
          'tint-sun': 'var(--surface-tint-sun)',
          'tint-coral': 'var(--surface-tint-coral)',
          'pastel-sakura': 'var(--surface-pastel-sakura)',
          'pastel-sora': 'var(--surface-pastel-sora)',
          'pastel-wakatake': 'var(--surface-pastel-wakatake)',
          'pastel-yamabuki': 'var(--surface-pastel-yamabuki)',
          'pastel-shu': 'var(--surface-pastel-shu)',
          'pastel-matcha': 'var(--surface-pastel-matcha)',
          'pastel-fuji': 'var(--surface-pastel-fuji)',
        },
        border: {
          soft: 'var(--border-soft)',
          strong: 'var(--border-strong)',
          dashed: 'var(--border-dashed)',
          disabled: 'var(--border-disabled)',
        },
        text: {
          primary: 'var(--text-primary)',
          strong: 'var(--text-strong)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          'on-ink': 'var(--text-on-ink)',
          link: 'var(--text-link)',
          'link-hover': 'var(--text-link-hover)',
          danger: 'var(--text-danger)',
          success: 'var(--text-success)',
        },
        accent: {
          primary: 'var(--accent-primary)',
          'primary-ink': 'var(--accent-primary-ink)',
          secondary: 'var(--accent-secondary)',
          tertiary: 'var(--accent-tertiary)',
          sun: 'var(--accent-sun)',
          leaf: 'var(--accent-leaf)',
          brand: 'var(--brand-wordmark)',
          focus: 'var(--focus-ring)',
        },
        status: {
          'draft-bg': 'var(--status-draft-bg)',
          'draft-ink': 'var(--status-draft-ink)',
          'draft-edge': 'var(--status-draft-edge)',
          'published-bg': 'var(--status-published-bg)',
          'published-ink': 'var(--status-published-ink)',
          'published-edge': 'var(--status-published-edge)',
          'cancelled-bg': 'var(--status-cancelled-bg)',
          'cancelled-ink': 'var(--status-cancelled-ink)',
          'cancelled-edge': 'var(--status-cancelled-edge)',
          'completed-bg': 'var(--status-completed-bg)',
          'completed-ink': 'var(--status-completed-ink)',
          'completed-edge': 'var(--status-completed-edge)',
        },
        rsvp: {
          'going-bg': 'var(--rsvp-going-bg)',
          'going-ink': 'var(--rsvp-going-ink)',
          'going-edge': 'var(--rsvp-going-edge)',
          'maybe-bg': 'var(--rsvp-maybe-bg)',
          'maybe-ink': 'var(--rsvp-maybe-ink)',
          'maybe-edge': 'var(--rsvp-maybe-edge)',
          'notgoing-bg': 'var(--rsvp-notgoing-bg)',
          'notgoing-ink': 'var(--rsvp-notgoing-ink)',
          'notgoing-edge': 'var(--rsvp-notgoing-edge)',
          'cancelled-bg': 'var(--rsvp-cancelled-bg)',
          'cancelled-ink': 'var(--rsvp-cancelled-ink)',
          'cancelled-edge': 'var(--rsvp-cancelled-edge)',
          'none-bg': 'var(--rsvp-none-bg)',
          'none-ink': 'var(--rsvp-none-ink)',
          'none-edge': 'var(--rsvp-none-edge)',
        },
        vis: {
          'public-bg': 'var(--vis-public-bg)',
          'public-ink': 'var(--vis-public-ink)',
          'public-edge': 'var(--vis-public-edge)',
          'private-bg': 'var(--vis-private-bg)',
          'private-ink': 'var(--vis-private-ink)',
          'private-edge': 'var(--vis-private-edge)',
        },
        cap: {
          ok: 'var(--cap-ok)',
          near: 'var(--cap-near)',
          full: 'var(--cap-full)',
          track: 'var(--cap-track)',
        },
      },
      screens: {
        xs: '360px',
        sm: '480px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      keyframes: {
        'sticker-press': {
          '0%': { transform: 'scale(1) rotate(var(--sticker-tilt, 0deg))' },
          '45%': { transform: 'scale(.86) rotate(calc(var(--sticker-tilt, 0deg) - 2deg))' },
          '100%': { transform: 'scale(1) rotate(var(--sticker-tilt, 0deg))' },
        },
        'hanko-thump': {
          '0%': { transform: 'scale(1.6) rotate(-14deg)', opacity: '0' },
          '55%': { transform: 'scale(.92) rotate(-5deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(-6deg)', opacity: '1' },
        },
        'page-turn-in': {
          '0%': { transform: 'perspective(1600px) rotateY(-6deg) translateX(18px)', opacity: '0' },
          '60%': { opacity: '1' },
          '100%': { transform: 'perspective(1600px) rotateY(0deg) translateX(0)', opacity: '1' },
        },
        'daruma-wobble': {
          '0%,100%': { transform: 'rotate(-2deg)' },
          '50%': { transform: 'rotate(2deg)' },
        },
        'neko-beckon': {
          '0%,100%': { transform: 'rotate(-8deg)' },
          '50%': { transform: 'rotate(8deg)' },
        },
        'koi-spin': { to: { transform: 'rotate(360deg)' } },
        'kokeshi-nod': {
          '0%,100%': { transform: 'rotate(-4deg)' },
          '50%': { transform: 'rotate(4deg)' },
        },
        'skeleton-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'toast-in': {
          '0%': { transform: 'translateY(12px) rotate(-3deg)', opacity: '0' },
          '70%': { transform: 'translateY(-2px) rotate(-1deg)', opacity: '1' },
          '100%': { transform: 'translateY(0) rotate(-1.2deg)', opacity: '1' },
        },
        'modal-in': {
          '0%': { transform: 'translateY(14px) scale(.97)', opacity: '0' },
          '100%': { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'sheet-up': {
          from: { transform: 'translateY(16px)', opacity: '0' },
          to: { transform: 'none', opacity: '1' },
        },
        'drawer-in': {
          from: { transform: 'translateX(-16px)', opacity: '0' },
          to: { transform: 'none', opacity: '1' },
        },
        'view-fade': { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      animation: {
        'sticker-press': 'sticker-press var(--dur-fast) var(--ease-press)',
        'hanko-thump': 'hanko-thump var(--dur-stamp) var(--ease-press)',
        'page-turn-in': 'page-turn-in var(--dur-page-turn) var(--ease-page-turn) both',
        'daruma-wobble': 'daruma-wobble var(--dur-idle-wobble) var(--ease-bob) infinite',
        'neko-beckon': 'neko-beckon var(--dur-idle-beckon) var(--ease-bob) infinite',
        'koi-spin': 'koi-spin var(--dur-idle-koi) linear infinite',
        'kokeshi-nod': 'kokeshi-nod var(--dur-idle-nod) var(--ease-bob) infinite',
        'skeleton-shimmer': 'skeleton-shimmer 1.4s linear infinite',
        'toast-in': 'toast-in var(--dur-medium) var(--ease-press)',
        'modal-in': 'modal-in var(--dur-medium) var(--ease-paper)',
        'sheet-up': 'sheet-up var(--dur-drawer) var(--ease-paper)',
        'drawer-in': 'drawer-in var(--dur-drawer) var(--ease-paper)',
        'view-fade': 'view-fade var(--dur-base) var(--ease-paper)',
      },
    },
  },
  plugins: [],
}

export default config
